// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  jQuery(function() {
    var ChooseYourDestination, MarkerConnector, chooser, lat, lng, map, marker, _ref;
    ChooseYourDestination = (function() {

      function ChooseYourDestination(map, selector, marker) {
        this.map = map;
        this.selector = selector;
        this.marker = marker;
        this.activate = __bind(this.activate, this);

        this.drop = __bind(this.drop, this);

        jQuery(this.selector).on("click", this.activate);
        this.marker = L.marker();
      }

      ChooseYourDestination.prototype.drop = function(mouse_evt) {
        this.marker.setLatLng(mouse_evt.latlng);
        this.marker.addTo(this.map);
        return this.map.off("click", this.drop);
      };

      ChooseYourDestination.prototype.activate = function(event) {
        return this.map.on("click", this.drop);
      };

      return ChooseYourDestination;

    })();
    MarkerConnector = (function() {

      function MarkerConnector(marker_start, marker_end) {
        this.marker_start = marker_start;
        this.marker_end = marker_end;
      }

      return MarkerConnector;

    })();
    _ref = [69.20148, 13.97096], lat = _ref[0], lng = _ref[1];
    navigator.geolocation.getCurrentPosition(function(location) {
      lat = location.coords.latitude;
      lng = location.coords.longitude;
      marker.setLatLng([lat, lng]);
      return map.panTo([lat, lng]);
    });
    map = L.map('wrapper').setView([lat, lng], 17);
    chooser = new ChooseYourDestination(map, "#destination-chooser");
    L.tileLayer('http://{s}.tile.cloudmade.com/f15cc60d60784f14ad4586a462a675c3/997/256/{z}/{x}/{y}.png', {
      attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://cloudmade.com">CloudMade</a>',
      maxZoom: 17
    }).addTo(map);
    return marker = L.marker([lat, lng]).addTo(map);
  });

}).call(this);
